//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLendBorrow
    {
        public Nullable<int> IdClient { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Lend { get; set; }
        public Nullable<decimal> Borrow { get; set; }
        public Nullable<int> CustId { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Lmdt { get; set; }
    }
}
