//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatioCalculationHDR
    {
        public Nullable<int> IdClient { get; set; }
        public int RatioId { get; set; }
        public Nullable<System.DateTime> CrashingDate { get; set; }
        public Nullable<decimal> PurchaseCarryingCost { get; set; }
        public Nullable<decimal> MillCrashingCost { get; set; }
        public Nullable<decimal> EmptySackCost { get; set; }
        public Nullable<decimal> SalesCarryingCost { get; set; }
        public Nullable<decimal> SackSewingCost { get; set; }
        public Nullable<decimal> SutliCost { get; set; }
        public Nullable<decimal> KuliCost { get; set; }
        public Nullable<decimal> KayelCost { get; set; }
        public Nullable<decimal> TrolleyCost { get; set; }
        public Nullable<decimal> ChadaCost { get; set; }
        public Nullable<decimal> KhajnaCost { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> TotalProducedQty { get; set; }
        public Nullable<decimal> ProducedPerUnit { get; set; }
        public Nullable<decimal> CostPerSack { get; set; }
        public string Remarks { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
