//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRatioCalculationDTL
    {
        public Nullable<int> IdClient { get; set; }
        public int RatioId { get; set; }
        public int SupplierId { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> TotalSacks { get; set; }
        public Nullable<decimal> TotalMon { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Userid { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
